services:

  traefik:
    image: traefik:latest
    container_name: traefik
    # ports:
    #   - 8000:80
    #   - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml

  whoami:
    image: traefik/whoami
    container_name: simple-service
