services:
  traefik:
    image: traefik:v3.2
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
      #- /var/log:/var/log
    command:
      - --api.dashboard=true
      - --log.level=INFO
      #- --log.filepath=/var/log/traefik.log
      - --accesslog=true
      #- --accesslog.filepath=/var/log/traefik-access.log
      - --providers.docker.network=proxy
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entryPoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.asDefault=true 
      - --entrypoints.websecure.http.tls.certresolver=myresolver
      - --certificatesresolvers.myresolver.acme.email=toj320@gmail.com
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    labels:
      - traefik.enable=true
      - traefik.http.routers.mydashboard.rule=HostRegexp(`^(traefik.).+`)
      - traefik.http.routers.mydashboard.service=api@internal
      - traefik.http.routers.mydashboard.middlewares=myauth
      - "traefik.http.middlewares.myauth.basicauth.users=test:$$2y$$05$$DnmoPZ6q9.OXwGIFvyZSJ.S/DT5osBCQQEo808DPEds.R0BglY6kW"

  breadsauce:
    image: tieje/breadsauce:latest
    ports:
      - 443:443
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.breadsauce.rule=HostRegexp(`^(breadsauce.).+`)

networks:
  proxy:
    name: proxy

volumes:
  letsencrypt:
    name: letsencrypt
