---
- name: Ensure Docker
  hosts: web_servers
  become: true
  vars:
    gpg_path: /etc/apt/keyrings/docker.asc
  tasks:

    - name: Ensure no conflicting dependencies
      ansible.builtin.apt:
        state: absent
        name:
          - docker.io
          - docker-doc
          - docker-compose
          - docker-compose-v2
          - podman-docker
          - containerd
          - runc

    - name: Set up docker apt repo
      ansible.builtin.apt:
        state: present
        name:
          - ca-certificates
          - curl

    - name: Ensure the keyring directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    
    - name: Add docker gpg key
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/{{ ansible_facts["distribution"] }}/gpg"
        dest: "{{ gpg_path }}"
        mode: '0444'
        force: true

    - name: 
