---
# ansible-playbook playbooks/uninstall_docker.yml -i inventory/web_servers.yml
- name: Uninstall docker
  hosts: web_servers
  become: true
  gather_facts: false
  tasks:

    - name: Purge docker
      ansible.builtin.apt:
        state: absent
        purge: true
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - docker-ce-rootless-extras
    
    - name: Remove docker directories
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      loop:
        - /var/lib/docker
        - /var/lib/containerd
        - /etc/apt/sources.list.d/docker.list
        - /etc/apt/keyrings/docker.asc
